
services:
  postgres-user:
    image: postgres:13
    container_name: postgres-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - microservice-net

  postgres-company:
    image: postgres:13
    container_name: postgres-company
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - microservice-net

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      users-service:
        condition: service_started
      company-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - microservice-net


  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres-user
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - microservice-net

  company-service:
    build:
      context: ./company-service
      dockerfile: Dockerfile
    container_name: company-service
    ports:
      - "8090:8090"
    depends_on:
      - postgres-company
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-company:5432/companydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge
